# Generated by Django 5.0.6 on 2024-06-16 18:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artist.artistmodel'),
        ),
        migrations.AlterField(
            model_name='albummodel',
            name='release_date',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
    ]
