# Generated by Django 5.0.6 on 2024-06-16 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_albummodel_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 16, 18, 22, 58, 2346, tzinfo=datetime.timezone.utc)),
        ),
    ]
