# Generated by Django 5.0.6 on 2024-06-16 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_albummodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
